<?php
echo "Name: ";
//echo $_SESSION['id'];
echo $name;
echo $br;
echo $hr;
echo "Health: ";
echo $health; echo "%<progress class='progress-health' value=\"$health\" max=\"100\"></progress>";
echo $br;
echo $hr;
echo "Country: ";
echo $country;
echo $br;
echo $hr;
echo "Rank: ";
echo $rank;
echo $br;
echo $hr;
echo "Progress: ";
echo $rankprogress; echo "%<progress class='progress-rank' value=\"$rankprogress\" max=\"100\"></progress>";
echo $br;
echo $hr;
echo "You have $";
echo number_format($cash, 0, '.', ',');
echo " cash";
echo $br;
echo $hr;
echo "You have $";
echo number_format($bank, 0, '.', ',');
echo " in the bank";
echo $br;
echo $hr;
echo "You have ";
echo number_format($power, 0, '.', ',');
echo " power";
echo $br;
echo $hr;
echo "You have ";
echo number_format($bullets, 0, '.', ',');
echo " bullets";
echo $br;
echo $hr;
echo "You have ";
echo number_format($hoes, 0, '.', ',');
echo " crates";
echo $br;
echo $hr;
echo "You have ";
echo number_format($homies, 0, '.', ',');
echo " homies";
echo $br;
echo $hr;
echo "You have ";
echo number_format($credits, 0, '.', ',');
echo " credits";
echo $br;